name: CI

on:
  push:
    branches: [ '**' ]

jobs:

  php:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer update

      - name: Run tests
        run: composer test

  node:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  phpunit:
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:2

      - name: Clone MediaWiki
        run: git clone --depth 1 -b REL1_43 https://gerrit.wikimedia.org/r/mediawiki/core.git .

      - name: Install dependencies
        run: composer update

      - name: Composer require
        run: |
          REPO="${{ github.event.repository.name }}"
          PACKAGE="${REPO#mwstake-}"
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          composer require "mwstake/${PACKAGE}:dev-${BRANCH}" --prefer-source

      - name: Create LocalSettings.php
        run: echo '<?php $wgServer = "";' > LocalSettings.php

      - name: Run tests
        run: |
          REPO="${{ github.event.repository.name }}"
          PACKAGE="${REPO#mwstake-}"
          composer phpunit:unit -- --colors=always "vendor/mwstake/${PACKAGE}/tests/phpunit/unit" --exclude-group Broken,ParserFuzz,Stub
